[package]
name = "experimentor"
version = "0.1.0"
authors = ["Wouter Nederhof"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
actix-web = "3"
rand = "0.7.3"
rand_pcg = "0.2.0"
